Field Hunt/src/objects/Hub_Membership__c.object
<CustomObject>
    <description>Contains records that indicate what Hub groups a person is a member of.</description>
    <fields>
        <fullName>Hub_Group_ID__c</fullName>
        <label>Hub Group ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hub_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Hub_Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub Membership</label>
    <nameField>
        <displayFormat>HUB-{000000}</displayFormat>
        <label>Hub Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hub Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Field Hunt/src/classes/HubMembershipTest.cls
@isTest(SeeAllData = true)
public class HubMembershipTest {

    static testMethod void newHubMemberTest() {
    test.startTest();
        //Create a new CollaborationGroupMember instance
        CollaborationGroupMember cgm = new CollaborationGroupMember();
        
        //Fill with data
        cgm.CollaborationGroupID = [SELECT Id
                                    FROM CollaborationGroup
                                    WHERE Name = 'Test Group' LIMIT 1].Id;
        cgm.MemberID = [SELECT Id
                        FROM User
                        WHERE Username = 'luciano22@gmail.com' LIMIT 1].Id;
        
        //Insert the list       
        insert(cgm);
        
        //Pull a Hub Membership and make sure it matches
        String newID;
        
        newID = [SELECT Id 
                FROM Hub_Membership__c 
                WHERE Hub_User__c = :cgm.MemberID AND Hub_Group_ID__c = :cgm.CollaborationGroupID].Id;
        
        System.assert(string.isnotblank(newID));
        
        cgm = [SELECT Id, CollaborationGroupID, MemberID
            FROM CollaborationGroupMember
            WHERE CollaborationGroupID = :cgm.CollaborationGroupID AND MemberID = :cgm.MemberID];
        
        delete(cgm);
        
        Hub_Membership__c  hm = new Hub_Membership__c();
        
        hm = [SELECT Id, IsDeleted
            FROM Hub_Membership__c
            WHERE Hub_User__c = :cgm.MemberID AND Hub_Group_ID__c = :cgm.CollaborationGroupID LIMIT 1 ALL ROWS];
        
        System.assertEquals(hm.IsDeleted, true);
        
        test.stopTest();
     }    
     
}